# Generated by BehavEd
# ( "comment" )
check = getGameFlag("murder2", 3 )
if check == 0
     startCutScene("FALSE", "FALSE" )
     cameraFade(1.000, 1.000 )
     waittimed ( 1.000 )
     moveHeroesToEnt("hero_spot_tent" )
     act("phoenix_npc", "phoenix_npc" )
     cameraFocusToEntity("jean_place01", 384.000, 45.000, 150.000, 0.000 )
     waittimed ( 0.750 )
     cameraFocusToEntity("jean_place01", 288.000, 30.000, 135.000, 2.000 )
     cameraFade(0.000, 1.000 )
     waittimed ( 0.750 )
     startCharConversation("act2/murder/murder2/2_murder2_020", "cyclops", "act2/murder/murder2/2_murder2_022" )
else
     # ( "does the player have the coin--should clowns come in?" )
     check_coin = getGameFlag("murder2", 7 )
     if check_coin == 0
          # ( "coin hasn't been picked up--is clown assault in progress?" )
          check_prog = getGameFlag("murder2", 9 )
          if check_prog == 0
               # ( "no--initiate clown assault" )
               setGameFlag("murder2", 9, 1 )
               startCutScene("FALSE", "FALSE" )
               cameraFade(1.000, 1.000 )
               waittimed ( 1.000 )
               moveHeroesToEnt("hero_spot_tent" )
               cameraFocusToEntity("arcade_coin", 256.000, 45.000, 90.000, 0.000 )
               waittimed ( 0.500 )
               cameraFocusToEntity("arcade_coin", 192.000, 35.000, 45.000, 2.000 )
               cameraFade(0.000, 0.250 )
               waittimed ( 0.750 )
               act("clown_car_stop", "clown_car_stop" )
               setInvisible("arcade_coin", "FALSE" )
               setEnable("trig_coin", "TRUE" )
               waittimed ( 3.000 )
               endCutScene("FALSE", "TRUE" )
          else
               lockControls(-1.000 )
               cameraFade(1.000, 1.000 )
               waittimed ( 1.000 )
               moveHeroesToEnt("hero_spot_tent" )
               waittimed ( 0.750 )
               cameraFade(0.000, 1.000 )
               lockControls(0.100 )
          endif
     else
          lockControls(-1.000 )
          cameraFade(1.000, 1.000 )
          waittimed ( 1.000 )
          moveHeroesToEnt("hero_spot_tent" )
          waittimed ( 0.750 )
          cameraFade(0.000, 1.000 )
          lockControls(0.100 )
     endif
endif

