# Generated by BehavEd
# ( "This script decide which conversation to play for the character" )
shiar_done = getObjective("shiar_obj70", "COMPLETE" )
skrull_done = getObjective("skrull_obj10", "COMPLETE" )
# ( "Camera change" )
lockControls(1.000 )
cameraFade(1.000, 0.250 )
waittimed ( 0.250 )
cameraFocusToEntity("Karnak_cam", 250.000, 25.000, 190.000, 0.000 )
waittimed ( 0.100 )
copyOAndANonActivators("bw_herowait04", "bw_herowait05", "bw_herowait06" )
copyOriginAndAngles("_ACTIVATOR_", "talk_lockjaw" )
waittimed ( 0.100 )
heroID = getID("_ACTIVATOR_" )
setZoneVar("atLockjaw", heroID )
hero_name = getName("_ACTIVATOR_" )
if hero_name == "spiderman"
     playanim (  "EA_ZONE1", "_ACTIVATOR_", "LOOP", "" )
else
     playanim (  "EA_TALKING_03", "_ACTIVATOR_", "LOOP", "" )
endif
cameraFade(0.000, 0.250 )
waittimed ( 0.100 )
waittimed ( 0.250 )
if skrull_done != 0
     # ( "part3" )
     startConversation("act4/attilan/4_attilan1_570" )
# elif shiar_done  != 0
     # ( "part2" )
     startConversation("act4/attilan/4_attilan1_370" )
else
     # ( "part1" )
     # ( "This is unlocked from the started." )
     hero_name = getName("_ACTIVATOR_" )
     if hero_name == "spiderman"
          startConversation("act4/attilan/4_attilan1_072" )
     else
          # startConversation("act4/attilan/4_attilan1_070" )
          startConversation("act4/attilan/4_attilan1_370" )
     endif
endif

