# Generated by BehavEd
# ( "This is a spawn script" )
setSegmentVisible("_OWNER_", "20102_Mgun_segment", "0" )
setSegmentVisible("_OWNER_", "20102_Mgun_back_segment", "0" )
setSegmentVisible("_OWNER_", "20102_pistol_segment", "0" )
setSegmentVisible("_OWNER_", "20102_knife_R_hand_segment", "0" )
state = randomInt(2, 10 )
if state <= 3
     # ( "She is sitting at the conference table" )
     copyOriginAndAngles("_OWNER_", "chair_spot03" )
     playanim (  "EA_ZONE3", "_OWNER_", "LOOP", "" )
     setZoneVar("bw", 1 )
     # ( " This turns on the 3D Vo conversation" )
     act("3Dvo_fury_bw", "" )
else
     # ( "She is sitting at the conference table" )
     copyOriginAndAngles("_OWNER_", "chair_spot03" )
     playanim (  "EA_ZONE3", "_OWNER_", "LOOP", "" )
     setZoneVar("bw", 1 )
     # ( " This turns on the 3D Vo conversation" )
     act("3Dvo_fury_bw", "" )
endif

