# Generated by BehavEd
startCutScene("TRUE", "FALSE" )
waittimed ( 0.500 )
moveHeroesToEnt("hero_spot02" )
cameraMove(" 2029.060 8003.500 549.470 ", 0.000 )
cameraPan(" 0.000 44.000 260.000 ", 0.000, "FALSE" )
cameraFade(0.000, 0.500 )
waittimed ( 1.000 )
nightcrawlerdlc = isActorOnTeam("nightcrawlerdlc" )
if nightcrawlerdlc == 1
     startConversation("act2/mephisto/mephisto2/2_mephisto2_211_DLC" )
else
     startCharConversation("act2/mephisto/mephisto2/2_mephisto2_210", "THOR", "act2/mephisto/mephisto2/2_mephisto2_211" )
endif
setEnable("trigger_soul_swap", "TRUE" )

