# Generated by BehavEd
setGameFlag("mephisto2", 3, 1 )
strange_on_team = isActorOnTeam("drstrange" )
if strange_on_team == 1
     startConversation("act2/mephisto/mephisto2/2_mephisto2_232" )
else
     endCutScene("FALSE", "TRUE" )
     loadZone("mephisto3", "link_mephisto3" )
endif

