# Generated by BehavEd
# ( "This checks of the player is Dr. Strange" )
player = isActorOnTeam("anyone" )

if player == 0
     act("drstrange_door", "" )
else
     # ( "Wong needs to tell the player they can't enter Dr. Strange room" )
     # ( "******************Conversation stuff******************" )
     # ( "***********************Get the name of Player**************************" )
     pc_name = getID("_ACTIVATOR_" )
     # ( "****This passes the name of the player to the next script****" )
     setZoneVar("player", pc_name )
     # ( "***********************End get the name of Player**************************" )
     # ( "******************Script Fu******************" )
     # ( "The _OWNER_ in this script will be the _ACTIVATOR_ of the next script" )
     # ( "The second parm is the camera focus!!!!!!!!!!!" )
     act("conv_cam", "door_" )
     # ( "This wait need to be long enough to all the camera it get into position" )
     # ( "*********************************************************************************************" )
     waittimed ( 1.000 )
     # ( "*********************************************************************************************" )
     startConversation("act2/strange/2_strange1_110" )
endif

