# Generated by BehavEd

nightcrawler_freed = getGameFlag("mephisto3", 2 )
if nightcrawler_freed == 1

	# ( "PERSISTENCE--indicate phoenix has been saved" )
	setGameFlag("mephisto3", 1, 1 )

	# ( "release phoenix" )
	cameraFocusToEntity("lock_phoenix", 320.000, 45.000, 225.000, 1.500 )
	waittimed ( 1.500 )
	spawnEffect("phoenix_npc", "char/magneto/p3_power", " 0.000 0.000 40.000 ", " 0.000 0.000 0.000 " )
	sound (  "PLAY_SOUND", "char/magnet_m/p2_charge", "phoenix_npc", "" )
	spawnEffect("lock_phoenix", "char/magneto/p3_power", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
	waittimed ( 1.500 )
	act("lock_phoenix", "lock_phoenix" )
	act("cage_open_p", "cage_open_p" )
	remove ( "trig_phoenix", "trig_phoenix" )
	remove ( "trig_phoenix_no", "trig_phoenix_no" )
else

	# ( "PERSISTENCE--indicate nightcrawler has been saved" )
	setGameFlag("mephisto3", 2, 1 )

	# ( "release nightcrawler" )
	cameraFocusToEntity("lock_nightcrawler", 320.000, 45.000, 45.000, 1.500 )
	waittimed ( 1.500 )
	spawnEffect("nightcrawler", "char/magneto/p3_power", " 0.000 0.000 40.000 ", " 0.000 0.000 0.000 " )
	sound (  "PLAY_SOUND", "char/magnet_m/p2_charge", "phoenix_npc", "" )
	spawnEffect("lock_nightcrawler", "char/magneto/p3_power", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
	waittimed ( 1.500 )
	act("lock_nightcrawler", "lock_nightcrawler" )
	act("cage_open_n", "cage_open_n" )
	remove ( "trig_nightcrawler", "trig_nightcrawler" )
	remove ( "trig_nightcrawler_no", "trig_nightcrawler_no" )

endif

# These values are later in the game used to check if a person is alive:
# Contrary to previous comments, a value of "1" actually means that Nightcrawler is dead: 
setGameFlag("mephisto3", 1, 0 )
# Contrary to previous comments, a value of "1" actually means that Phoenix is dead:
setGameFlag("mephisto3", 2, 0 )
# Unlock Nightcrawler as usable character:
unlockCharacter("nightcrawlerdlc", "04" )
waittimed ( 0.100 )
unlockCharacter("Phoenix", "" )

waittimed ( 1.000 )
endCutScene("FALSE", "TRUE" )
waittimed ( 1.000 )
if nightcrawler_freed == 1
	startConversation("act2/mephisto/mephisto3/2_mephisto3_055m" )
else
	startConversation("act2/mephisto/mephisto3/2_mephisto3_053m" )