# Generated by BehavEd
setRecallActive("TRUE" )
remove ( "fff_fire_med", "fff_fire_med" )
remove ( "fff_fire", "fff_fire" )
remove ( "gunship", "gunship" )
remove ( "gunship_fast", "gunship_fast" )
setEnable("fff_shoot_me", "TRUE" )
first_load = getGameFlag("heli4", 1 )
beat_fff = getGameFlag("bosses", 2 )
if first_load == 0
     startConversation("act1/heli/heli4/1_HELI4_010" )
     setGameFlag("heli4", 1, 1 )
endif
if beat_fff == 1
     remove ( "dead_turbine", "dead_turbine" )
     remove ( "fff_intro", "fff_intro" )
     killEntitySilent("fff_destroy01" )
     killEntitySilent("thingy01" )
     killEntitySilent("fff_destroy02" )
     killEntitySilent("thingy02" )
     killEntitySilent("fff_destroy03" )
     killEntitySilent("thingy03" )
endif

