# Generated by BehavEd
# ( "If this is set to 1, then the player gave the right password" )
pwd_good = getGameFlag("conv_vars", 25 )
if pwd_good == 1
     # ( "The payer needs to be reward for figuring out the password" )
     awardXPToPlayable(200 )
     # ( "This makes sure that the start condition is run only once" )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

