# Generated by BehavEd
cameraSetClipPlane(8000.000 )
mephisto_intro_conv = getGameFlag("mephisto1", 1 )
if mephisto_intro_conv == 0
     setGameFlag("mephisto1", 1, 1 )
     
     magneto = isActorOnTeam("Magneto" )
     if magneto == 1
	startConversation("act2/mephisto/mephisto1/2_MEPHISTO1_012_DLC" ) 
     else
     	startCharConversation("act2/mephisto/mephisto1/2_MEPHISTO1_010", "ICEMAN", "act2/mephisto/mephisto1/2_MEPHISTO1_012" )
     endif
endif
phoenix_kidnapped = getGameFlag("mephisto2", 1 )
if phoenix_kidnapped == 1
     remove ( "phoenix_conv_trig", "phoenix_conv_trig" )
     remove ( "phoenix_npc", "phoenix_npc" )
     remove ( "phoenix_counter", "phoenix_counter" )
endif
lava_puzzle = getGameFlag("mephisto1", 2 )
if lava_puzzle == 1
     copyOriginAndAngles("lava_force_field", "lava_force_field_spot" )
     act("altar_candle04", "altar_candle04" )
endif
power_puzzle = getGameFlag("mephisto1", 3 )
if power_puzzle == 1
     copyOriginAndAngles("power_force_field", "power_force_field_spot" )
     act("altar_candle02", "altar_candle02" )
endif
grave_puzzle = getGameFlag("mephisto1", 4 )
if grave_puzzle == 1
     copyOriginAndAngles("grave_force_field", "grave_force_field_spot" )
     act("altar_candle05", "altar_candle05" )
endif
sacrifice_puzzle = getGameFlag("mephisto1", 5 )
if sacrifice_puzzle == 1
     copyOriginAndAngles("sacrifice_force_field", "sacrifice_force_field_spot" )
     act("altar_candle03", "altar_candle03" )
endif
brazier_puzzle = getGameFlag("mephisto1", 6 )
if brazier_puzzle == 1
     copyOriginAndAngles("brazier_force_field", "brazier_force_field_spot" )
     act("altar_candle01", "altar_candle01" )
     remove ( "brazier_fire04", "brazier_fire04" )
     remove ( "brazier_fire03", "brazier_fire03" )
     remove ( "brazier_fire01", "brazier_fire01" )
     remove ( "brazier_fire06", "brazier_fire06" )
endif
phoenix_teleport = getGameFlag("mephisto1", 7 )
all_puzzle = getGameFlag("mephisto1", 8 )
if all_puzzle == 1
     act("altar_portal_fx", "altar_portal_fx" )
     setEnable("link_mephisto2", "TRUE" )
endif

