# Generated by BehavEd
# ( "Mephisto's pain script" )
# ( "see if the hero hit him with a weapon and make the hero drop it, giving mephisto health back." )
wep = getHeldWeapon("_ACTIVATOR_" )
if wep == "the_weapon"
     dropWeapon("_ACTIVATOR_", "FALSE" )

     #special condition: make Mephisto lose life if NC and Jean alive
     jeandead = getGameFlag("mephisto3", 2 )
     ncdead = getGameFlag("mephisto3", 1 )
     if jeandead == 0
         if ncdead == 0
     	     painthresh = getZoneVar("painthresh" )
	     painthresh = isub(painthresh, 20 )
	     setZoneVar("painthresh", painthresh )
         endif
     endif

     remove ( "hint_trigger", "hint_trigger" )
endif
# ( "see if he's holding some guy up and hurting him and make him stop" )
hurting = getZoneVar("hurting" )
if hurting == 1
     setZoneVar("hurting", 0 )
     setCombatNode("mephisto", "power_smash2" )
endif
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
painthresh = getZoneVar("painthresh" )
painthreshf = fdiv(painthresh, 100.000 )
hamt = fdiv(health, healthmax )
if hamt <= painthreshf
     newhealth = fmul(painthreshf, healthmax )
     setHealth("_OWNER_", newhealth )
     if painthresh >= 50
          orbdropped = getZoneVar("orbdropped" )
          if orbdropped == 0
               setZoneVar("orbdropped", 1 )
               setPatternSequence("_OWNER_", "mephisto_sword" )
               act("enable_hint", "enable_hint" )
          endif
     elif painthresh == 25
          # ( "heals himself here" )
          setPatternSequence("mephisto", "mephisto_heal" )
          setZoneVar("laststage", 1 )
     else
	  # if both heroes alive, display special ending:
	  jeandead = getGameFlag("mephisto3", 2 )
	  ncdead = getGameFlag("mephisto3", 1 )
	  if jeandead == 0
		if ncdead == 0
		    setCombatNode("mephisto", "power_smash2" )
		    act( "nightcrawler_spawner", "nightcrawler_spawner" )
                    display ( "DEAD HERO" )
                    setZoneVar("over", 1 )
                    startCutScene("TRUE", "FALSE" )
                    copyOriginAndAngles("mephisto", "mr_mephisto_spot02" )
                    copyOriginAndAngles("dead_hero", "dead_hero_spot" )
                    moveHeroesToEnt("outro_spot" )
                    cameraMove(" 1150.750 -3518.930 -34.860 ", 0.000 )
                    cameraPan(" 0.000 25.200 240.100 ", 0.000, "FALSE" )
                    cameraFade(0.000, 0.500 )
                    waittimed ( 0.500 )
  		    startConversation("act2/mephisto/mephisto4/2_mephisto4_029" )
		    remove ( "nightcrawler_spawner", "nightcrawler_spawner" )
		    act("phoenix_spawner", "phoenix_spawner" )
		else
	          # ( "dead here" )
        	  display ( "DEAD MEPHISTO" )
	          setCombatNode("_OWNER_", "deathgen" )
		endif
	  else
          	# ( "dead here" )
          	display ( "DEAD MEPHISTO" )
          	setCombatNode("_OWNER_", "deathgen" )
	  endif
     endif
endif

