# Generated by BehavEd
# ( "Mephisto's pain script" )
# ( "see if the hero hit him with a weapon and make the hero drop it, giving mephisto health back." )
wep = getHeldWeapon("_ACTIVATOR_" )
if wep == "the_weapon"
     dropWeapon("_ACTIVATOR_", "FALSE" )
     remove ( "hint_trigger", "hint_trigger" )
endif
# ( "see if he's holding some guy up and hurting him and make him stop" )
hurting = getZoneVar("hurting" )
if hurting == 1
     setZoneVar("hurting", 0 )
     setCombatNode("mephisto", "power_smash2" )
endif
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
painthresh = getZoneVar("painthresh" )
painthreshf = fdiv(painthresh, 100.000 )
hamt = fdiv(health, healthmax )
if hamt <= painthreshf
     newhealth = fmul(painthreshf, healthmax )
     setHealth("_OWNER_", newhealth )
     if painthresh >= 50
          orbdropped = getZoneVar("orbdropped" )
          if orbdropped == 0
               setZoneVar("orbdropped", 1 )
               setPatternSequence("_OWNER_", "mephisto_sword" )
               act("enable_hint", "enable_hint" )
          endif
     elif painthresh == 25
          # ( "heals himself here" )
          setPatternSequence("mephisto", "mephisto_heal" )
          setZoneVar("laststage", 1 )
     else
          # ( "dead here" )
          display ( "DEAD MEPHISTO" )
          setCombatNode("_OWNER_", "deathgen" )
     endif
endif

