# Generated by BehavEd
# ( "0.5" )
setAIActive("mephisto", "FALSE" )
waittimed ( 1.000 )
cameraMove(" 589.700 -3685.800 55.780 ", 0.000 )
cameraPan(" 0.000 25.100 51.400 ", 0.000, "FALSE" )

jeandead = getGameFlag("mephisto3", 2 )
ncdead = getGameFlag("mephisto3", 1 )
if jeandead == 1
	startConversation("act2/mephisto/mephisto4/2_mephisto4_022" )
elif ncdead == 1
	startConversation("act2/mephisto/mephisto4/2_mephisto4_022" )
else
	startConversation("act2/mephisto/mephisto4/2_mephisto4_022m" )
endif
