# Generated by BehavEd
# ( "0.5" )
setAIActive("mephisto", "FALSE" )
waittimed ( 1.000 )
cameraMove(" 589.700 -3685.800 55.780 ", 0.000 )
cameraPan(" 0.000 25.100 51.400 ", 0.000, "FALSE" )
startConversation("act2/mephisto/mephisto4/2_mephisto4_022" )

