# Generated by BehavEd
# ( "comment" )
setAIActive("_OWNER_", "FALSE" )
fade("_OWNER_", 0.000, 0.000, "TRUE" )
setNoCollide("_OWNER_", "TRUE" )
setInvulnerable("_OWNER_", "TRUE" )
# ( "play anim" )
jeandead = getGameFlag("mephisto3", 2 )
if jeandead == 1
     playanim (  "EA_ZONE2", "_OWNER_", "STOP", "" )
else
     playanim (  "EA_ZONE1", "_OWNER_", "STOP", "" )
endif

