# Generated by BehavEd
# ( "rhino banter" )
isVenomhere = isActorOnTeam("venom" )
if isVenomhere == 1
     startConversation("act2/murder/murder3/2_murder3_032_DLC" )
else    
     startCharConversation("act2/murder/murder3/2_murder3_030", "thing", "act2/murder/murder3/2_murder3_032" )
endif
