# Generated by BehavEd
# ( "zone script" )
setRecallActive("FALSE" )

setSegmentVisible("Magneto", "helmet_segment", "0")

waittimed ( 0.250 )
murder_done = getObjective("Murder_Obj40", "COMPLETE" )
if murder_done == 1
     copyOriginAndAngles("clea", "clea_sitting" )
     playanim (  "EA_ZONE2", "clea", "LOOP", "" )
     second_intro = getGameFlag("strange", 12 )
     if second_intro == 0
          setGameFlag("strange", 19, 1 )
          setGameFlag("strange", 12, 1 )
          cameraFocusToEntity("weasel_intro_cam", 50.000, 15.000, 180.000, 0.500 )
          startConversation("act2/strange/2_strange2_220" )
     else
          setWaypointPath("weasel", "weasel_talk", 1 )
     endif
else
     intro = getGameFlag("strange", 11 )
     if intro == 0
          setGameFlag("strange", 19, 1 )
          setGameFlag("strange", 11, 1 )
          cameraFocusToEntity("clea", 120.000, 15.000, 180.000, 0.500 )
          startConversation("act2/strange/2_strange2_010" )
     else
          setWaypointPath("weasel", "weasel_talk", 1 )
          copyOriginAndAngles("clea", "clea_sitting" )
          playanim (  "EA_ZONE2", "clea", "LOOP", "" )
     endif
endif
spawn_ghostrider = getObjective("mephisto_obj30", "COMPLETE" )
if spawn_ghostrider == 1
     act("sp_ghostridersimple01", "" )
endif
book_ready = getObjective("strange_obj30", "HIDDEN" )
if book_ready == 0
     got_book = getGameFlag("strange", 2 )
     if got_book == 1
          remove ( "vision_book", "" )
          remove ( "green_book", "" )
     else
          setEnable("vision_book", "TRUE" )
     endif
endif
