# Generated by BehavEd
# ( "This script is called after the Professor X conversation has ended" )
mephisto_done = getObjective("Mephisto_Obj70", "COMPLETE" )
if mephisto_done == 1
     playanim (  "EA_TALKING_02", "profx_char", "LOOP", "" )
else
     playanim (  "EA_ZONE13", "profx_char", "LOOP", "" )
     addBolton("_OWNER_", "models/bolton/cerebro_helm", "Bip01 Head", "", 1 )
     # ( "Turn on the effect" )
     act("effect_profx", "" )
endif
faceEntity("profx_char", "jean_seat" )
# ( "This script also needs to reset camera" )
cameraReset( )
# ( "And put the characters back into their poses" )
playanim (  "EA_ZONE2", "jeangrey", "LOOP", "" )

