# Generated by BehavEd
# ( "This script is called after the conversations in the Sanctum" )
# ( "Turn off 3D Vo" )
# ( "This script also needs to reset camera" )
cameraReset( )
# ( "And put the characters back into their poses" )
faceEntity("jeangrey", "profx_char" )
playanim (  "EA_ZONE2", "jeangrey", "LOOP", "" )
faceEntity("hankpym", "orb_object" )
playanim (  "EA_ZONE7", "hankpym", "LOOP", "" )
faceEntity("fury", "orb_of_agamotto" )
setAIActive("vision", "TRUE" )
setWaypointPath("vision", "occultroom", 1 )

