# Generated by BehavEd
# ( "This script decide which conversation to play for the character" )
atlantis_done = getObjective("atlantis_obj60", "COMPLETE" )
# ( "This script decide which conversation to play for the character" )
lockControls(1.000 )
cameraFade(1.000, 0.150 )
waittimed ( 0.150 )
setAIActive("weasel", "FALSE" )
copyOriginAndAngles("jarvis", "wp_weaselpath07" )
copyOriginAndAngles("_ACTIVATOR_", "weasel_heroact" )
copyOriginAndAngles("weasel", "wp_weaselpath02" )
copyOAndANonActivators("tony_Herowait01", "tony_herowait02", "tony_herowait03" )
faceEntity("weasel", "_ACTIVATOR_" )
waittimed ( 0.100 )
cameraFocusToEntity("weasel_cam", 150.000, 15.000, 60.000, 0.000 )
waittimed ( 0.100 )
cameraFade(0.000, 0.250 )
waittimed ( 0.250 )
if atlantis_done != 0
     # ( "part3" )
     startConversation("act1/stark/1_stark2_522" )
     objective ( "stark_obj70",  "EOBJCMD_COMPLETE" )
else
     # ( "part2" )
     # ( "This is unlocked from the started." )
     startConversation("act1/stark/1_stark2_322" )
     objective ( "stark_obj10",  "EOBJCMD_COMPLETE" )
endif

