# Generated by BehavEd
# ( "comment" )
startCutScene("FALSE", "FALSE" )
waittimed ( 0.500 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
act("move_here01", "move_here01" )
act("dark_cap", "dark_cap" )
act("dark_colossus", "dark_colossus" )
waittimed ( 0.100 )
cameraMove(" 1500.000 6772.510 148.690 ", 0.100 )
cameraPan(" 0.000 41.100 90.000 ", 0.100, "FALSE" )
waittimed ( 1.000 )
cyclops = isActorOnTeam("Cyclops" )
storm = isActorOnTeam("Storm" )
ironman = isActorOnTeam("IronMan" )
if cyclops == 1
     startConversation("act5/doom/doom2/5_doom2_036_DLC" )
else 
     if storm == 1
          startConversation("act5/doom/doom2/5_doom2_034" )
     else
	  if ironman == 1
		startConversation("act5/doom/doom2/5_doom2_036" )
	   else
		startCharConversation("act5/doom/doom2/5_doom2_030", "CaptainAmerica", "act5/doom/doom2/5_doom2_032" )
	   endif
     endif
endif

