# Generated by BehavEd
# ( "This is the load script for Vahalla1" )

setSegmentVisible("Magneto", "helmet_segment", "0")

# unused variable "valhalla1" will mark if Jean and NC are alive:
nc_dead = getGameFlag("mephisto3", 1 )
jean_dead = getGameFlag("mephisto3", 2 )
if nc_dead == 1
    setGameFlag("valhalla1", 6, 0 )
elif jean_dead == 1
    setGameFlag("valhalla1", 6, 0 )
else
    setGameFlag("valhalla1", 6, 1 )
endif

waittimed ( 0.500 )
setCurrentAct(3 )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
cameraSetClipPlane(20000.000 )
# ( "****************Unlock the objective categories****************" )
addObjectiveCategory("act3_asgard" )
addObjectiveCategory("act3_bifrost" )
addObjectiveCategory("act3_niffleheim" )
# ( "****************END Unlock the objective categories****************" )
valhalla = getGameFlag("valhalla1", 1 )
if valhalla == 0
     waittimed ( 0.250 )
     cameraFocusToEntity("camera_target", 168.000, 14.000, 180.000, 0.250 )
     moveHeroesToEnt("nick03" )
     setGameFlag("valhalla1", 1, 1 )
     cameraFade(0.000, 1.000 )
     startConversation("act3/valhalla/3_valhalla1_010" )
else
     cameraFade(0.000, 0.000 )
endif
bifrost_done = getObjective("bifrost_obj10", "COMPLETE" )
asgard_done = getObjective("asgard_obj40", "COMPLETE" )
if asgard_done == 1
     # ( "********The link to vahalla2 is open if either bifrost OR Asgard missions are complete********" )
     open_door = getGameFlag("valhalla1", 9 )
     if open_door == 1
          act("open_valhalla", "" )
     else
          setHintType("guard", "importanttalk" )
     endif
     # ( "********END The link to vahalla2 is open if either bifrost OR Asgard missions are complete********" )
     # ( "*************************************" )
     # ( "This opens the gate back to asgard" )
     setEnable("effect_simmer02", "TRUE" )
     setEnable("link_asgard1a", "TRUE" )
     act("effect_simmer02", "effect_simmer02" )
     # ( "*************************************" )
     # ( "****************Move Focus into place****************" )
     copyOriginAndAngles("upgrade_focus01", "spawn_focus" )
     # ( "****************End Move Focus into place****************" )
     asgard_intro = getGameFlag("valhalla1", 4 )
     if bifrost_done == 1
          # ( "Used to check if niffle_ready should equal 1" )
          setGameFlag("valhalla1", 7, 1 )
     elif asgard_intro == 0
          setGameFlag("valhalla1", 4, 1 )
          # ( "This setsup the intro camera" )
          act("intro_setup", "" )
          startConversation("act3/valhalla/3_valhalla1_014" )
     endif
     # ( "*************************************************" )
endif
# ( "*************************************" )
# ( "This is really only for debug, because the intro should be played from another conversation" )
if bifrost_done == 1
     # ( "*************************************************" )
     # ( "This spawns the bifrost warriors!" )
     act("spawn_warrior", "" )
     # ( "*************************************************" )
     # ( "********The link to vahalla2 is open if either bifrost OR Asgard missions are complete********" )
     open_door = getGameFlag("valhalla1", 9 )
     if open_door == 1
          act("open_valhalla", "" )
     else
          setHintType("guard", "importanttalk" )
     endif
     # ( "********END The link to vahalla2 is open if either bifrost OR Asgard missions are complete********" )
     # ( "****************Move Focus into place****************" )
     copyOriginAndAngles("upgrade_focus01", "spawn_focus" )
     # ( "****************End Move Focus into place****************" )
     # ( "*************************************************" )
     bifrost_intro = getGameFlag("valhalla1", 3 )
     if asgard_done == 1
          # ( "Used to check if niffle_ready should equal 1" )
          setGameFlag("valhalla1", 7, 1 )
     elif bifrost_intro == 0
          setGameFlag("valhalla1", 3, 1 )
          # ( "This setsup the intro camera" )
          act("intro_setup", "" )
          startConversation("act3/valhalla/3_valhalla1_012" )
     endif
     # ( "*************************************************" )
     # ( "*************************************************" )
endif
# ( "*************************************" )
niffle_ready = getGameFlag("valhalla1", 7 )
if niffle_ready == 1
     # ( "*****************If both bifrost and asgard are done, then niffleheim*****************" )
     niffle_open = getObjective("niffleheim_obj10", "HIDDEN" )
     setEnable("link_niffleheim1", "TRUE" )
     setEnable("well_helvelgamar", "FALSE" )
     if niffle_open == 1
          niffle_intro = getGameFlag("valhalla1", 5 )
          if niffle_intro == 0
               setGameFlag("valhalla1", 5, 1 )
               # ( "This setsup the intro camera" )
               act("intro_setup", "" )
               startConversation("act3/valhalla/3_valhalla1_510" )
          endif
     endif
endif

