# Generated by BehavEd
# ( "Turns lever and statue, then gets rotation of both statues" )
# ( "zoneflag = 0 = no rotation = south" )
# ( "zoneflag = 1 = turned 90 degrees = east" )
# ( "zoneflag = 2 = turned 180 degrees = north" )
# ( "zoneflag = 3 = turned 270 degrees = west" )
startCutScene("FALSE", "FALSE" )
copyOriginAndAngles("_ACTIVATOR_", "lev1_null" )
playanim (  "EA_ZONE3", "_ACTIVATOR_", "NONE", "" )
act("rot_lever1", "rot_lever1" )
waittimed ( 1.000 )
cameraFocusToEntity("cam_statue1", 512.000, 35.000, 0.000, 1.000 )
waittimed ( 1.000 )
act("rot_statue1", "rot_statue1" )
# ( "Math to set ZoneVar to current rotation" )
rotation1 = getZoneVar("statue1" )
newrotation = iadd(rotation1, 1 )
# ( "If the 'newrotation' value is 4, set zonevar to 0 since a full 360 turn has occured" )
# ( "If not, set the zonevar to the newrotation" )
if newrotation == 4
     setZoneVar("statue1", 0 )
else
     setZoneVar("statue1", newrotation )
endif
# ( "see if statues are in the correct rotations" )
# ( "if they are, do some cool stuff" )
rotation1 = getZoneVar("statue1" )
rotation2 = getZoneVar("statue2" )
if rotation1 == 3
     if rotation2 == 2
          remove ( "trigger_lever1", "trigger_lever1" )
          remove ( "trigger_lever2", "trigger_lever2" )
          cameraFade(1.000, 1.000 )
          waittimed ( 1.000 )
          cameraFocusToEntity("bigdoor", 600.000, 35.000, 90.000, 0.000 )
          cameraFade(0.000, 1.000 )
          waittimed ( 1.500 )
          killEntity("bigdoor" )
          waittimed ( 1.000 )
          cameraFade(1.000, 1.000 )
          waittimed ( 1.000 )
          cameraReset( )
          waittimed ( 0.100 )
          cameraFade(0.000, 1.000 )
          waittimed ( 1.000 )
     else
          waittimed ( 3.000 )
     endif
else
     waittimed ( 3.000 )
endif
# ( "End the cutscene!" )
endCutScene("FALSE", "TRUE" )

