# Generated by BehavEd
# ( "This loads atlantis1" )
# ( "A mission briefing is only played once" )
# ( "It can be loaded again via the review computer" )
mb_once = getGameFlag("mb", 3 )
if mb_once == 0
     # ( "This loads the mission briefing" )
     setGameFlag("mb", 3, 1 )
     startMovie("mb03", "afterMovie" )
     waitsignal ( "afterMovie" )
endif
loadZone("act1/atlantis/atlantis1", "link_atlantis1" )

