# Generated by BehavEd
# ( "Zone script for doomstark1" )
# ( "****************Unlock the objective categories****************" )
addObjectiveCategory("act5_doom" )
# ( "****************END Unlock the objective categories****************" )
cameraSetClipPlane(10000.000 )
setCurrentAct(5 )
setSegmentVisible("Magneto", "helmet_segment", "0")
# ( "****************Check which console is used****************" )
review = getGameFlag("dstark", 9 )
training = getGameFlag("dstark", 10 )
trivia = getGameFlag("dstark", 11 )
if review == 1
     setEnable("mission_review", "FALSE" )
endif
if training == 1
     setEnable("mission_training", "FALSE" )
endif
if trivia == 1
     setEnable("mission_trivia", "FALSE" )
endif
# ( "****************END Check which console is used****************" )
intro = getGameFlag("dstark", 1 )
if intro == 0
     setGameFlag("dstark", 1, 1 )
     waittimed ( 0.250 )
     setEnable("fury", "FALSE" )
     startCutScene("FALSE", "FALSE" )
     setInvisible("_ALL_HEROES_", "TRUE" )
     setInvisible("fury", "TRUE" )
     cameraMove(" 255.530 750.820 603.650 ", 0.000 )
     cameraPan(" 0.000 38.000 235.200 ", 0.000, "FALSE" )
     waittimed ( 1.000 )
     setSegmentVisible("fury", "gun_left_segment", "0" )
     setSegmentVisible("fury", "gun_right_segment", "0" )
     cameraFade(0.000, 1.000 )
     waittimed ( 0.750 )
     spawnEffect("_HERO1_", "map/atilan/lockjaw_teleport_victim", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     spawnEffect("_HERO2_", "map/atilan/lockjaw_teleport_victim", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     spawnEffect("_HERO3_", "map/atilan/lockjaw_teleport_victim", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     spawnEffect("_HERO4_", "map/atilan/lockjaw_teleport_victim", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     spawnEffect("fury", "map/atilan/lockjaw_teleport_victim", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.750 )
     hero1 = alive("_HERO1_" )
     hero2 = alive("_HERO2_" )
     hero3 = alive("_HERO3_" )
     hero4 = alive("_HERO4_" )
     if hero1 == 1
          setInvisible("_HERO1_", "FALSE" )
     endif
     if hero2 == 1
          setInvisible("_HERO2_", "FALSE" )
     endif
     if hero3 == 1
          setInvisible("_HERO3_", "FALSE" )
     endif
     if hero4 == 1
          setInvisible("_HERO4_", "FALSE" )
     endif
     setInvisible("fury", "FALSE" )
     waittimed ( 1.250 )
     endCutScene("FALSE", "false" )
     objective ( "doom_obj0",  "EOBJCMD_SHOW" )
     objective ( "doom_obj10",  "EOBJCMD_SHOW" )
     startConversation("act5/doomstark/5_doomstark1a_010" )
else
     link_open = getObjective("doomstark_obj20", "HIDDEN" )
     if link_open == 0
          setEnable("bridge_railing", "TRUE" )
          waittimed ( 0.250 )
          remove ( "fury", "" )
     endif
     cameraFade(0.000, 0.000 )
     # ( "This unlocks the extraction point" )
     extractionUnlock("" )
endif
setWaypointPath("fury", "gofury", 1 )
waittimed ( 1.000 )
faceEntity("fury", "_ACTIVE_HERO_" )

