startMovie("cine01","waitSignal")
waitsignal("waitSignal")
unlockCharacter("hawkeye", "" )
unlockCharacter("cyclops", "" )
unlockCharacter("magneto", "" )
unlockCharacter("sabretooth", "" )
unlockCharacter("venom", "" )
unlockCharacter("ronin", "" )
unlockCharacter("captainmarvel", "" )
unlockCharacter("moonknight", "" )
unlockCharacter("Bishop", "" )
unlockCharacter("Gambit", "" )
unlockCharacter("Juggernaut_Hero", "" )
unlockCharacter("pyro_hero", "" )
unlockCharacter("Rogue", "" )
unlockCharacter("ScarletWitch", "" )
unlockCharacter("Toad_hero", "" )
unlockCharacter("Beast", "" )
unlockCharacter("emma_frost_hero", "" )
unlockCharacter("Jubilee", "" )
unlockCharacter("Magma", "" )
unlockCharacter("Psylocke_Hero", "" )
unlockCharacter("cable", "" )
unlockCharacter("darkphoenix", "" )
unlockCharacter("XMan", "" )
unlockCharacter("sunfire", "" )
unlockCharacter("Cannonball", "" )
loadMapStartGame()

