# Generated by BehavEd
# ( "comment" )
cameraToLocationAngles(" 4749.000 1180.000 1800.000 ", " 4749.000 1180.000 212.000 ", 0.000 )
setAmbientLightColor(" 0.800 0.800 0.800 ", 0.100 )
setMusicOverride("music/toy5_x", 2.000 )
setRecallActive("FALSE" )

