# Generated by BehavEd
# ( "comment" )
act("effect_boom", "effect_boom" )
setEnable("harm_hint", "TRUE" )
waittimed ( 0.100 )
act("harm_hint", "harm_hint" )
waittimed ( 1.000 )
act("effect_boom", "effect_boom" )
waittimed ( 0.250 )
magneto = isActorOnTeam("magneto" )
if magneto == 1
     startConversation( "act2/murder/murder5/2_murder5_012_DLC" )
else
     startCharConversation("act2/murder/murder5/2_murder5_010", "elektra", "act2/murder/murder5/2_murder5_012" )
endif
