# Generated by BehavEd
# ( "gladiator" )
beatim = getGameFlag("bosses", 25 )
if beatim == 0
     setRecallActive("FALSE" )
     setMusicOverride("music/shiar2_x", 1.000 )
     act("gladiator_spawner", "gladiator_spawner" )
     setRecallActive("FALSE" )
     metim = getGameFlag("bosses", 24 )
     if metim == 0
          waittimed ( 0.010 )
          setAIActive("gladiator", "FALSE" )
          setGameFlag("bosses", 24, 1 )
          startCutScene("FALSE", "FALSE" )
          cameraMove(" 9141.440 4499.070 139.350 ", 0.500 )
          cameraPan(" 0.000 24.600 257.000 ", 0.500, "FALSE" )
          Sabretooth = isActorOnTeam("Sabretooth" )
	  if Sabretooth == 1
		startConversation("act4/shiar/shiar2/4_shiar2_072_DLC" ) 
	  else
		startCharConversation("act4/shiar/shiar2/4_shiar2_070", "ICEMAN", "act4/shiar/shiar2/4_shiar2_072" )
	  endif          
     endif
else
     remove ( "the_core", "the_core" )
     setEnable("boss_switch01", "FALSE" )
     setEnable("boss_switch02", "FALSE" )
     setEnable("boss_switch03", "FALSE" )
     setEnable("boss_switch04", "FALSE" )
     remove ( "platform_force_field_1", "platform_force_field_1" )
     remove ( "platform_force_field_2", "platform_force_field_2" )
endif

