# Generated by BehavEd
# ( "First encounter skrull spawnscript" )
# ( "What's my name?" )
myname = getName("_OWNER_" )
# ( "'devi' + 'myname' = name of waypoint to go to" )
wpname = strcatstr("devi", myname )
# ( "Don't attempt to attack heroes" )
setNoTarget("_OWNER_", "TRUE" )
# ( "Go to your waypoint" )
waittimed ( 0.500 )
setWaypointPath("_OWNER_", wpname, 1 )

