# Generated by BehavEd
# ( "Zone script for doomstark1b" )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
setCurrentAct(5 )
setSegmentVisible("Magneto", "helmet_segment", "0")
# ( "****************Unlock the objective categories****************" )
addObjectiveCategory("act5_doom" )
# ( "****************END Unlock the objective categories****************" )
act("bridge_railing", "bridge_railing" )
cameraSetClipPlane(10000.000 )
waittimed ( 1.500 )
cameraFade(0.000, 1.000 )
intro = getGameFlag("dstark", 3 )
if intro == 0
     startCutScene("FALSE", "FALSE" )
     setGameFlag("dstark", 3, 1 )
     setEnable("fury", "FALSE" )
     setEnable("blackwidow", "FALSE" )
     setEnable("vision", "FALSE" )
     setEnable("hankpym", "FALSE" )
     cameraFocusToEntity("fury", 150.000, 15.000, 0.000, 0.000 )
     # ( "pitch 13.4, yaw 270" )
     waittimed ( 1.000 )
     cameraFade(0.000, 1.000 )
     waittimed ( 2.000 )
     startConversation("act5/doomstark/5_doomstark1b_010" )
else
     copyOriginAndAngles("fury", "wp_nick04" )
     cameraFade(0.000, 0.000 )
endif
enable_gizmos = getGameFlag("dstark", 7 )
if enable_gizmos == 1
     setEnable("gizmo01", "TRUE" )
     setEnable("gizmo02", "TRUE" )
endif
remove_giz1 = getGameFlag("dstark", 5 )
if remove_giz1 == 1
     remove ( "gizmo01", "" )
endif
remove_giz2 = getGameFlag("dstark", 6 )
if remove_giz2 == 1
     remove ( "gizmo02", "" )
endif
# ( "This able the portal" )
setRecallActive("TRUE" )

