unlockCharacter("drstrange", "" )
unlockCharacter("blade", "" )
unlockCharacter("ghostrider", "" )
unlockCharacter("daredevil", "" )
unlockCharacter("blackpanther", "" )
unlockCharacter("nickfury", "" )
unlockCharacter("silversurfer", "" )
unlockCharacter("hawkeye", "" )
unlockCharacter("hulk", "" )
unlockCharacter("cyclops", "" )
unlockCharacter("nightcrawlerdlc", "" )
unlockCharacter("doomdlc", "" )
unlockCharacter("magneto", "" )
unlockCharacter("sabretooth", "" )
unlockCharacter("venom", "" )
unlockCharacter("ronin", "" )
unlockCharacter("blackwidowv", "" )
unlockCharacter("captainmarvel", "" )
unlockCharacter("moonknight", "" )
unlockCharacter("colossus", "" )
unlockCharacter("Bishop", "" )
unlockCharacter("Gambit", "" )
unlockCharacter("Juggernaut_Hero", "" )
unlockCharacter("Phoenix", "" )
unlockCharacter("ProfessorX", "" )
unlockCharacter("pyro_hero", "" )
unlockCharacter("Rogue", "" )
unlockCharacter("ScarletWitch", "" )
unlockCharacter("Toad_Hero", "" )
unlockCharacter("Beast", "" )
unlockCharacter("emma_frost_hero", "" )
unlockCharacter("Jubilee", "" )
unlockCharacter("Magma", "" )
unlockCharacter("Psylocke_Hero", "" )
unlockCharacter("cable", "" )
unlockCharacter("DarkPhoenix", "" )
unlockCharacter("XMan", "" )
unlockCharacter("sunfire", "" )
unlockCharacter("Cannonball", "" )
loadZoneAddTeam("act1/heli/heli1", "link_heli1" )
extractionUnlock("act1/stark/stark1" )
extractionUnlock("act1/heli/heli1" )
extractionUnlock("act1/heli/heli2" )
extractionUnlock("act1/heli/heli3" )
extractionUnlock("act1/omega/omega1" )
extractionUnlock("act1/omega/omega3" )
extractionUnlock("act1/atlantis/atlantis2" )
extractionUnlock("act1/atlantis/atlantis4" )
extractionUnlock("act1/atlantis/atlantis5" )
extractionUnlock("act1/mandarin/mandarin1" )
extractionUnlock("act1/mandarin/mandarin3" )
extractionUnlock("act2/strange/strange1" )
extractionUnlock("act2/murder/murder2" )
extractionUnlock("act2/murder/murder3" )
extractionUnlock("act2/mephisto/mephisto1" )
extractionUnlock("act2/mephisto/mephisto3" )
extractionUnlock("act3/valhalla/valhalla1" )
extractionUnlock("act3/bifrost/bifrost2" )
extractionUnlock("act3/asgard/asgard1" )
extractionUnlock("act3/asgard/asgard3" )
extractionUnlock("act3/niffleheim/niffleheim1" )
extractionUnlock("act3/niffleheim/niffleheim2" )
extractionUnlock("act3/niffleheim/niffleheim3" )
extractionUnlock("act4/attilan/attilan1" )
extractionUnlock("act4/shiar/shiar1" )
extractionUnlock("act4/shiar/shiar2" )
extractionUnlock("act4/shiar/shiar4" )
extractionUnlock("act4/skrull/skrull2" )
extractionUnlock("act4/skrull/skrull4" )
extractionUnlock("act5/doomstark/doomstark1b" )
extractionUnlock("act5/doom/doom1" )
extractionUnlock("act5/doom/doom2" )
extractionUnlock("act5/doom/doom3" )
extractionUnlock("act5/doom/doom4" )
