# Generated by BehavEd
# ( "comment" )
beat = getGameFlag("bosses", 31 )
if beat == 0
     setRecallActive("FALSE" )
     act("sp_drdoom01", "sp_drdoom01" )
     # ( "check if stage 1 is complete" )
     checkpoint = getGameFlag("bossCP", 10 )
     if checkpoint == 1
          remove ( "sp_humantorch", "sp_humantorch" )
          remove ( "sp_thing", "sp_thing" )
          remove ( "sp_mrfantastic", "sp_mrfantastic" )
          remove ( "sp_invisiblewoman", "sp_invisiblewoman" )
          waittimed ( 0.200 )
          setDefaultTarget("drdoom" )
          # ( "check if stage 2 is complete" )
          checkpoint = getGameFlag("bossCP", 11 )
          moveHeroesToEnt("player_start" )
          cameraMove(" 975.520 1012.370 234.000 ", 0.000 )
          cameraPan(" 0.000 33.500 289.000 ", 0.000, "FALSE" )
          waittimed ( 0.100 )
          if checkpoint == 1
               # ( "start last stage" )
               setInvulnerable("drdoom", "FALSE" )
               setActorScaleTimed("drdoom", 0.875, 0.000 )
               remove ( "blow_trigger", "blow_trigger" )
               remove ( "reset_beam", "reset_beam" )
               remove ( "doom_shield", "doom_shield" )
               act("stage3", "stage3" )
               copyOriginAndAngles("drdoom", "stage3spot" )
               cameraMove(" 1106.000 1340.800 96.800 ", 0.000 )
               cameraPan(" 0.000 19.200 105.000 ", 0.000, "FALSE" )
          else
               # ( "start stage2" )
               act("stage2", "stage2" )
               act("stage2", "stage2" )
               act("stage2", "stage2" )
               act("stage2", "stage2" )
               copyOriginAndAngles("drdoom", "throne" )
               setRotZ("drdoom", -1.570 )
               setCombatNode("drdoom", "power11" )
          endif
          waittimed ( 0.500 )
          cameraFade(0.000, 0.500 )
     else
          # ( "intro" )
          startCutScene("FALSE", "TRUE" )
          act("sp_invisiblewoman", "sp_invisiblewoman" )
          act("sp_humantorch", "sp_humantorch" )
          act("sp_thing", "sp_thing" )
          act("sp_mrfantastic", "sp_mrfantastic" )
          heroNoTarget("TRUE" )
          enemiesNoTarget("TRUE" )
          waittimed ( 0.500 )
          cameraFade(0.000, 1.000 )
          cameraMove(" 1403.490 675.900 333.170 ", 0.000 )
          cameraPan(" 0.000 39.100 162.300 ", 0.000, "FALSE" )
          waittimed ( 2.000 )
          cameraMove(" 1020.980 763.220 119.140 ", 1.000 )
          cameraPan(" 0.000 10.400 106.600 ", 1.000, "FALSE" )
          cameraFOV(34.800, 1.000 )
          waittimed ( 1.000 )
          endCutScene("FALSE", "FALSE" )
          
          DoomIsHere = isActorOnTeam("doomdlc" )
	  if DoomIsHere == 1
          	startConversation("act5/doom/doom5/5_doom5_114_dlc" )
          else
          	startConversation("act5/doom/doom5/5_doom5_100" )
          endif
          waittimed ( 0.100 )
          enemiesNoTarget("TRUE" )
          heroNoTarget("TRUE" )
     endif
else
     copyOriginAndAngles("xpoint", "xpointhere" )
     cameraFade(0.000, 1.000 )
endif

