# Generated by BehavEd
# ( "killed the dragon" )
beat = getGameFlag("bosses", 2 )
if beat == 0
     setEnable("into_leftside", "FALSE" )
endif
setZoneVar("fffhits", 1 )
waittimed ( 0.200 )
met_fff = getGameFlag("bosses", 1 )
if met_fff == 0
     setZoneVar("fffhits", 0 )
     setAIActive("finfangfoom", "FALSE" )
     setGameFlag("bosses", 1, 1 )
     startCutScene("FALSE", "FALSE" )
     copyOriginAndAngles("finfangfoom", "wp_deckland" )
     cameraMove(" 1868.180 8182.360 207.920 ", 0.500 )
     cameraPan(" 0.000 -9.200 92.000 ", 0.500, "FALSE" )
     setCombatNode("finfangfoom", "power7" )
     waittimed ( 3.000 )
     endCutScene("FALSE", "FALSE" )
     magneto = isActorOnTeam("Magneto" )
     if magneto == 1
        startConversation("act1/heli/heli4/1_HELI4_022_DLC" )  
     else
     	startCharConversation("act1/heli/heli4/1_HELI4_020", "drstrange", "act1/heli/heli4/1_HELI4_022" )
     endif
else
     setZoneVar("fffhits", 1 )
     setDefaultTarget("finfangfoom" )
     setAIActive("finfangfoom", "TRUE" )
     act("gunship_control", "gunship_control" )
endif
remove ( "_OWNER_", "_OWNER_" )
# ( "test code below" )

