# Generated by BehavEd
# ( "comment" )
setHintType("mcs_aux", "none" )
remove ( "gammabomb", "gammabomb" )
remove ( "banner", "banner" )
setHintType("ultron_display_omega_a01", "objective" )
objective ( "omega_obj70",  "EOBJCMD_COMPLETE" )
unlockCharacter("hulk", "" )
waittimed ( 0.500 )
loadSimulatorComicMission( "CMHULK" )
act("alsolocked", "alsolocked" )
act("door_prime", "door_prime" )

