# Generated by BehavEd
# ( "Enables the trigger to unlock the horn room door" )
remove ( "hd_door_clip", "hd_door_clip" )
remove ( "hd_forcefield", "hd_forcefield" )
waittimed ( 1.000 )
setEnable("horn_room_guys_trig", "TRUE" )
endCutScene("FALSE", "TRUE" )
objective ( "asgard_obj50",  "EOBJCMD_SHOW" )
objective ( "asgard_obj20",  "EOBJCMD_COMPLETE" )
setGameFlag("asgard1", 1, 1 )
# ( "Check if Tyr has been saved" )
asgard_obj2 = getObjective("asgard_obj30", "COMPLETE" )
if asgard_obj2 == 1
     objective ( "asgard_obj40",  "EOBJCMD_SHOW" )
endif

