# Generated by BehavEd
# ( "Introduces Rhino and Shocker" )
cameraMove(" 300.000 3510.000 220.000 ", 2.000 )
cameraPan(" 0.000 54.000 90.000 ", 2.000, "FALSE" )
waittimed ( 2.000 )
setWaypointPath("ultrarhino", "ultrarhinopath", 1 )
setWaypointPath("ultrashocker", "ultrashockerpath", 1 )

