# Generated by BehavEd
# ( "blackheart dies" )
freesouls = getZoneVar("freesouls" )
if freesouls < 0
     # ( "not really dead until all the souls are dead" )
     # ( "find a place to res blackheart" )
     setZoneVar("reshere", 1 )
     act("res_blackheart", "res_blackheart" )
     waittimed ( 0.250 )
     spawnEffect("blackheart", "map/mephisto/statue_soul_release", " 0.000 0.000 0.000 ", " 0.000 -90.000 0.000 " )
     remove ( "blackheart", "blackheart" )
else
     # ( "all souls are dead, he can die now." )
     setMusicOverride("", 1.000 )
     awardAchievement("", "defeated_blackheart" )
     awardReputation("", 50 )
     setGameFlag("bosses", 17, 1 )
     remove ( "ff_cages", "ff_cages" )
     spawn("blackheart", "Blackheart_treasure", "treasure", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
endif

